[package]
name = "icfpc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
itertools = "0.13.0"
reqwest = "0.12.5"
tokio = { version = "1.38.0", features = ["full"] }

[dev-dependencies]
rstest = "0.21.0"
